
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 02 13:27:40 CEST 2018
//----------------------------------------------------

package serum;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GT_OP = 14;
  public static final int ELSE = 6;
  public static final int T_INT = 2;
  public static final int BOOL_LITERAL = 10;
  public static final int RPAREN = 25;
  public static final int LT_OP = 13;
  public static final int WHILE = 7;
  public static final int DIV_OP = 20;
  public static final int IDENTIFIER = 8;
  public static final int END_BLOCK = 29;
  public static final int AND_OP = 21;
  public static final int ASSIGN_OP = 11;
  public static final int SEPARATOR = 30;
  public static final int IF = 5;
  public static final int START_BLOCK = 28;
  public static final int LBRACKET = 26;
  public static final int LPAREN = 24;
  public static final int EQ_OP = 12;
  public static final int NOT_OP = 23;
  public static final int RBRACKET = 27;
  public static final int T_ARRAY = 4;
  public static final int EOF = 0;
  public static final int T_BOOL = 3;
  public static final int OR_OP = 22;
  public static final int SUM_OP = 17;
  public static final int error = 1;
  public static final int SUBS_OP = 18;
  public static final int INTEGER_LITERAL = 9;
  public static final int PROD_OP = 19;
  public static final int GET_OP = 16;
  public static final int LET_OP = 15;
}

